server:
  port: 8761
spring:
  application:
    name: spring-cloud-eureka
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: WEB
    sleuth:
      sampler:
        probability: 1.0

#security:
#  basic:
#    enabled: false #eureka用户是否认证
#  user:
#    name: eureka #eureka 用户名
#    password: eureka #eureka 密码

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/
    healthcheck:
      enabled : true
#    server:
#      enable-self-preservation: false   #false:注册中心关闭自我保护机制,生产时推荐打开
#      eviction-interval-timer-in-ms: 3000  #检查失效服务的时间,到达时间后移除失效注册应用