server:
  port: 9999
spring:
  application:
    name: kafka-consumer


kafka:
  autoCommitIntervalMs: 100
  autoOffsetReset: latest
  bachSize: 65536
  brokers: 172.20.2.114:9092
  bufferMemory: 524288
  concurrency: 12
  enabled: true
  group: neusoftTsp_energy
  heartbeatIntervalMs: 1500
  lingerMs: 1
  maxPollRecords: 20
  pollTimeout: 4000
  sessionTimeoutMs: 7500