spring:
  application:
    name: spring-cloud-admin
  security:
    user:
      name: "user"
      password: "password"

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      user.name: "user"         #These two are needed so that the server
      user.password: "password" #can access the protected client endpoints
  client:
    service-url:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/


server:
  port: 8083



management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS