spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-admin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #日志中显示sql语句
    #jpa默认建表时用的引擎为MyISAM，而MyISAM却是不支持事务的，要想支持需要将表的存储引擎设为InnoDB
    #设置表的存储引擎为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect